---
- name: Install ntp
  apt: name={{item}} state=present
  with_items:
  - ntp
  tags:
    - ntp-installation

- name: Configure ntp
  template: src=ntp.j2 dest=/etc/ntp.conf
#  notify: Restart ntp
  tags:
    - ntp-configuration

- name: Remove default time zone
  file: path=/etc/localtime state=absent
  changed_when: False
  tags:
    - ntp-configuration

- name: Set local time
  file: src=/usr/share/zoneinfo/{{pl_timezone}} dest=/etc/localtime state=link
  changed_when: False
  tags:
    - ntp-configuration
