---
- name: Add the elasticsearch APT repository key
  apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add the logstash APT repository
  apt_repository: repo="deb https://artifacts.elastic.co/packages/{{pl_logstash_major_version}}/apt stable main" state=present

- name: Install logstash
  apt: name={{item}} state=present force=yes
  with_items:
  - logstash

- name: Set logstash to start up by default
  systemd: name=logstash enabled=yes

- name: Create SSL directory for postfix
  file: path={{item}} state=directory
  with_items:
    - /etc/pki/tls/certs
    - /etc/pki/tls/private

- name: Copy logstash-forwarder.crt
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    #- { src: '{{pl_logstash_crt_src}}', dest: '{{pl_logstash_crt_dest}}' }
    #- { src: '{{pl_logstash_key_src}}', dest: '{{pl_logstash_key_dest}}' }
    - { src: '02-beats-input.conf.j2', dest: '/etc/logstash/conf.d/02-beats-input.conf' }
    - { src: '10-syslog-filter.conf.j2', dest: '/etc/logstash/conf.d/10-syslog-filter.conf' }
    - { src: '30-elasticsearch-output.conf.j2', dest: '/etc/logstash/conf.d/30-elasticsearch-output.conf' }
  notify: logstash restart

- name: Create directories
  file: path={{item}} state=directory group=logstash owner=logstash
  with_items:
    - "{{pl_logstash_logs}}"
    - "{{pl_logstash_data}}"

- name: Configure logstash
  replace: path=/etc/logstash/logstash.yml regexp="{{item.regexp}}" replace="{{item.replace}}" backup=yes
  with_items:
    - {regexp: "path.data{{':'}} /var/lib/logstash", replace: "path.data{{':'}} {{pl_logstash_data}}"}
    - {regexp: "path.logs: /var/log/logstash", replace: "path.logs{{':'}} {{pl_logstash_logs}}"}
  notify: logstash restart
