---
- name: Adding hadoop user
  user: name=hadoop groups=sudo,shadow shell=/bin/bash append=yes

- name: Adding hadoop user to sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='^%hadoop' line='%hadoop ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: Setup password less SSH for hadoop user
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: id_rsa.j2, dest: /home/hadoop/.ssh/id_rsa }
    - { src: id_rsa_pub.j2, dest: /home/hadoop/.ssh/id_rsa.pub }
    - { src: id_rsa_pub.j2, dest: /home/hadoop/.ssh/authorized_keys }

- name: Set HADOOP_HOME
  lineinfile: dest=/home/hadoop/.bashrc line="{{item}}"
  with_items:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - export PATH=$PATH:$JAVA_HOME/bin
  - export HADOOP_HOME=/opt/hadoop-2.6.3
  - export HADOOP_MAPRED_HOME=$HADOOP_HOME
  - export HADOOP_COMMON_HOME=$HADOOP_HOME
  - export HADOOP_HDFS_HOME=$HADOOP_HOME
  - export YARN_HOME=$HADOOP_HOME
  - export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
  - export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin
  - export HADOOP_INSTALL=$HADOOP_HOME

#- name: Download hadoop
#  get_url: url={{hadoop_url}} dest=/opt

- name: Copy hadoop binaries
  copy: src=Softwares/hadoop-2.6.3.tar.gz dest=/opt

- name: Extract hadoop
  unarchive: src=/opt/hadoop-2.6.3.tar.gz dest=/opt copy=no

- name: Set file permissions
  file: path=/opt/hadoop-2.6.3 owner=hadoop group=hadoop recurse=yes
