---
pl_flink_url: "https://archive.apache.org/dist/flink/flink-{{pl_flink_version}}/flink-{{pl_flink_version}}-bin-hadoop{{pl_flink_hadoop_version}}-scala_{{pl_flink_scala_version}}.tgz"
pl_flink_version: "1.4.0"
pl_flink_hadoop_version: "28"
pl_flink_scala_version: "2.11"
pl_flink_dir: "/opt"
