---
- name: Tag the hostname and ansible_groups to the instance
  ec2_tag:
    region: "{{aws_region}}"
    resource: "{{ansible_ec2_instance_id}}"
    state: present
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    tags: { "Name":"{{hostname}}", "ansible_groups":"{{group_names|join(',')}}" }

- name: Tag the Service to the instance
  ec2_tag:
    region: "{{aws_region}}"
    resource: "{{ansible_ec2_instance_id}}"
    state: present
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    tags: { "Service":"Tools" }
  when: '"admin-tools" in group_names'

- name: Tag the Service to the instance
  ec2_tag:
    region: "{{aws_region}}"
    resource: "{{ansible_ec2_instance_id}}"
    state: present
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    tags: { "Service":"Web Server" }
  when: '"web-server" in group_names'

- name: List the volumes for the instance
  ec2_vol:
    instance: "{{ansible_ec2_instance_id}}"
    region: "{{aws_region}}"
    state: list
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
  with_items: ec2.tagged_instances
  register: ec2vol

- name: Tag the root volume
  ec2_tag:
    region: "{{aws_region}}"
    resource: "{{ec2vol.results[0].volumes[0].id}}"
    state: present
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    tags: { "Name":"{{hostname}}", "ansible_groups":"{{group_names|join(',')}}", "Device":"{{ec2vol.results[0].volumes[0].attachment_set.device}}" }
