---
- hosts: '{{inventory}}'
  become: yes

  tasks:
  - name: Enalbe shard allocation
    shell: curl -XPUT localhost:9200/_all/_settings -d '{"index.routing.allocation.disable_allocation":"false" }'
