---
- hosts: '{{inventory}}'
  become: yes

  tasks:
  - name: Reboot server
    shell: reboot
    async: 0
    poll: 0

  - name: Wait for it to come back
    local_action: wait_for host={{ansible_ssh_host}} state=started port=22 delay=30 timeout=300 connect_timeout=15
