---
- name: Add the Salt source to the APT source list
  apt_repository: repo="ppa:saltstack/salt" state=present

- name: Install salt-master
  apt: name={{item}} state=present
  with_items:
   - salt-master
   - salt-cloud

- name: Configure salt-master
  template: src=master.j2 dest=/etc/salt/master

- name: Create pki directory
  file: path=/etc/salt/pki/master/minions state=directory

#- name: Copy pki keys
#  copy: src={{salt_pem}} dest=/etc/salt/pki/master/minions/salt.pem

#- name: Copy pki keys
#  copy: src={{salt_pub}} dest=/etc/salt/pki/master/minions/salt.pub

- name: Restart salt-master
  service: name=salt-master state=restarted
