---
- name: Install RKHunter and CHKRootKit
  apt: name={{item}} state=present
  with_items:
  - rkhunter
  - chkrootkit

- name: Create directory for RKHunter
  file: path=/var/log/rkhunter state=directory

- name: Configure logrotate for RKHunter
  template: src=rkhunter.j2 dest=/etc/logrotate.d/rkhunter

- name: Configure logrotate for CHKRootKit
  template: src=chkrootkit.j2 dest=/etc/logrotate.d/chkrootkit
