---
- name: Add repository
  apt_repository: repo={{item}} state=present
  with_items:
  - ppa:moka/stable
  - ppa:ravefinity-project/ppa

- name: Install themes
  apt: name={{item}} state=present
  with_items:
  - faba-mono-icons
  - faba-colors
  - moka-icon-theme
  - moka-gtk-theme
  - ambiance-flat-colors
  - radiance-flat-colors
