---
- name: Adding Kafka user
  user: name=kafka groups=sudo,shadow shell=/bin/bash append=yes generate_ssh_key=yes ssh_key_file=.ssh/id_rsa

- name: Download Kafka
  get_url: url={{kafka_url}} dest=/opt

- name: Extract Kafka
  unarchive: src=/opt/kafka_2.11-0.8.2.1.tgz dest=/opt copy=no

- name: Configure Kafka
  template: src=kafka.j2 dest=/opt/kafka_2.11-0.8.2.1/config/server.properties

- name: Configure Kafka
  template: src=kafka-run.j2 dest=/opt/kafka_2.11-0.8.2.1/bin/kafka-run-class.sh

- name: Create kafka logs directory
  file: path=/var/log/kafka-logs state=directory

- name: Configure logrotate for kafka
  template: src=kafka-log.j2 dest=/etc/logrotate.d/kafka

- name: Kafka init.d script
  template: src=kafka-script.j2 dest=/etc/init.d/kafka

- name: File permission
  shell: sudo chmod +x /etc/init.d/kafka

- name: Restart kafka
  service: name=kafka state=restarted

#- name: Start kafka
#  shell: sudo nohup /opt/kafka_2.11-0.8.2.1/bin/kafka-server-start.sh /opt/kafka_2.11-0.8.2.1/config/server.properties > /opt/kafka_2.11-0.8.2.1/kafka.log 2>&1 &
