---
- name: Adding nexus user
  user: name={{pl_nexus_user}} shell=/bin/bash append=yes generate_ssh_key=yes ssh_key_file=.ssh/id_rsa move_home=yes home={{pl_nexus_dir}}

- name: Download nexus
  unarchive: src='{{pl_nexus_download_url}}' dest='{{pl_nexus_dir}}' remote_src=yes group=nexus owner=nexus

- name: Configure nexus home
  lineinfile: dest="{{pl_nexus_dir}}/.bashrc" regexp="{{item.regexp}}" line="{{item.line}}" state=present backup=yes
  with_items:
    - { regexp: 'NEXUS_HOME', line: 'NEXUS_HOME={{pl_nexus_home}}' }

- name: Configure nexus user
  lineinfile: dest="{{pl_nexus_home}}/bin/nexus.rc" regexp="{{item.regexp}}" line="{{item.line}}" state=present backup=yes
  with_items:
    - { regexp: '#run_as_user', line: 'run_as_user="{{pl_nexus_user}}"' }

- name: Configure nexus java
  lineinfile: dest="{{pl_nexus_home}}/bin/nexus.vmoptions" regexp="{{item.regexp}}" line="{{item.line}}" state=present backup=yes
  with_items:
    - { regexp: '-Xms', line: '-Xms{{pl_nexus_xms}}' }
    - { regexp: '-Xmx', line: '-Xmx{{pl_nexus_xmx}}' }
    - { regexp: '-XX:MaxDirectMemorySize', line: '-XX:MaxDirectMemorySize={{pl_nexus_maxdirect}}' }

- name: Fix file permissions
  file: path={{pl_nexus_dir}} group=nexus owner=nexus recurse=yes

- name: Create symlink
  file: src={{item.src}} dest={{item.dest}} state=link
  with_items:
    - { src: '{{pl_nexus_home}}/bin/nexus', dest: '/etc/init.d/nexus' }

- name: Set nexus to start up by default
  service: name=nexus enabled=yes state=started

- name: Set nexus to start up by default
  systemd: name=nexus enabled=yes
