---
- name: Install MySql
  apt: name={{item}} state=present
  with_items:
   - mysql-server
   - mysql-client
   - python-mysqldb

- name: Configure MySql
  lineinfile: dest="/etc/mysql/mysql.conf.d/mysqld.cnf" regexp="{{item.regexp}}" line="{{item.line}}" state=present backup=yes
  with_items:
    - { regexp: 'bind-address', line: '#bind-address           = 0.0.0.0' }
  notify: restart mysql
