---
- name: Add LibreOffice repository
  apt_repository: repo="ppa:libreoffice/libreoffice-5-0" state=present

- name: Install LibreOffice
  apt: name={{item}} state=present
  with_items:
  - libreoffice
