---
- name: Add bitcoin APT repository
  apt_repository: repo="ppa:bitcoin/bitcoin" state=present

- name: Install bitcoin
  apt: name={{item}} state=present force=yes
  with_items:
  - bitcoin-qt
  - bitcoind
  - libcurl4-openssl-dev
  - libncurses5-dev
  - pkg-config
  - automake
  - yasm

- name: Adding bitcoin user
  user: name=bitcoin groups=sudo,shadow shell=/bin/bash append=yes generate_ssh_key=yes ssh_key_file=.ssh/id_rsa

- name: Adding bitcoin user to sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='^%bitcoin' line='%bitcoin ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: Create bitcoin directory
  file: path=/home/bitcoin/.bitcoin state=directory

- name: Configure bitcoin
  template: src=bitcoin.j2 dest=/home/bitcoin/.bitcoin/bitcoin.conf

- name: Deploy
  git: repo=git://github.com/pooler/cpuminer.git dest=/opt/cpuminer accept_hostkey=yes
