---
- name: Add the php7 source to the APT source list
  apt_repository: repo="ppa:ondrej/php" state=present
  tags:
    - php7-installation

- name: Install Php7
  apt: name={{item}} state=present
  with_items:
   - php7.0-fpm
   - php7.0-mysql
   - php7.0-curl
   - php7.0-gd
   - php7.0-json
   - php7.0-mcrypt
   - php7.0-opcache
   - php7.0-xml
   - php7.0-mbstring
  tags:
    - php7-installation

- name: Create /etc/php/7.0/fpm/conf.d/custom.ini
  file: path=/etc/php/7.0/fpm/conf.d/custom.ini state=touch

- name: Configure Php
  lineinfile: path=/etc/php/7.0/fpm/conf.d/custom.ini line="expose_php = off"
  notify: Restart Php
  tags:
    - php7-configuration
