---
- name: Add the grafana APT repository key
  apt_key: url=https://packagecloud.io/gpg.key state=present

- name: Add the grafana APT repository
  apt_repository: repo="deb https://packagecloud.io/grafana/stable/debian/ wheezy main" state=present

- name: Install grafana
  apt: name={{item}} state=present update_cache=yes
  with_items:
  - grafana

- name: Create folders
  file: path={{item}} state=directory group=grafana owner=grafana
  with_items:
    - "{{pl_grafana_home}}"
    - "{{pl_grafana_data}}"
    - "{{pl_grafana_logs}}"
    - "{{pl_grafana_plugins}}"

- name: Configure grafana
  template: src=grafana.ini.j2 dest=/etc/grafana/grafana.ini backup=yes
  notify: grafana restart

- name: Configure grafana service
  lineinfile: dest="/etc/init.d/grafana-server" regexp="{{item.regexp}}" line="{{item.line}}" state=present backup=yes
  with_items:
    #- { regexp: 'GRAFANA_HOME=', line: 'GRAFANA_HOME={{pl_grafana_home}}' }
    - { regexp: 'DATA_DIR=', line: 'DATA_DIR={{pl_grafana_data}}' }
    - { regexp: 'PLUGINS_DIR=', line: 'PLUGINS_DIR={{pl_grafana_plugins}}' }
    - { regexp: 'LOG_DIR=', line: 'LOG_DIR={{pl_grafana_logs}}' }
  notify: grafana restart

- name: Configure grafana service
  lineinfile: dest="/etc/default/grafana-server" regexp="{{item.regexp}}" line="{{item.line}}" state=present backup=yes
  with_items:
    #- { regexp: 'GRAFANA_HOME=', line: 'GRAFANA_HOME={{pl_grafana_home}}' }
    - { regexp: 'DATA_DIR=', line: 'DATA_DIR={{pl_grafana_data}}' }
    - { regexp: 'PLUGINS_DIR=', line: 'PLUGINS_DIR={{pl_grafana_plugins}}' }
    - { regexp: 'LOG_DIR=', line: 'LOG_DIR={{pl_grafana_logs}}' }
  notify: grafana restart

- name: Set grafana to start up by default
  systemd: name=grafana-server enabled=yes
