---
- name: Add the elasticsearch APT repository key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add the elasticsearch APT repository
  apt_repository: repo="deb https://artifacts.elastic.co/packages/{{pl_elasticsearch_major_version}}/apt stable main" state=present

- name: Install elasticsearch
  apt: name={{item}} state=present
  with_items:
  - elasticsearch={{pl_elasticsearch_minor_version}}
  notify: elasticsearch restart

- name: Set elasticsearch to start up by default
  systemd: name=elasticsearch enabled=yes

- name: Create directories
  file: path={{item}} state=directory group=elasticsearch owner=elasticsearch
  with_items:
    - "{{ht_data_path}}"
    - "{{ht_logs_path}}"

- name: Configure elasticsearch service
  lineinfile: dest="/usr/lib/systemd/system/elasticsearch.service" regexp="{{item.regexp}}" line="{{item.line}}" state=present backup=yes
  with_items:
    - { regexp: 'Environment=DATA_DIR', line: 'Environment=DATA_DIR={{ht_data_path}}' }
    - { regexp: 'Environment=LOG_DIR', line: 'Environment=LOG_DIR={{ht_logs_path}}' }
  notify: reload deamon

- name: Install x-pack
  elasticsearch_plugin: name=x-pack state=present

- name: Test for if xpack.security.enabled is present
  shell: grep "^xpack.security.enabled" /etc/elasticsearch/elasticsearch.yml
  register: checkxpack
  ignore_errors: yes

- name: Add xpack.security.enabled to properties
  lineinfile: dest=/etc/elasticsearch/elasticsearch.yml line='xpack.security.enabled{{':'}} false' state=present backup=yes
  when: checkxpack.rc == 1

- name: Configure elasticsearch
  lineinfile: dest="/etc/elasticsearch/elasticsearch.yml" regexp="{{item.regexp}}" line="{{item.line}}" state=present backrefs=yes backup=yes
  with_items:
    - { regexp: 'cluster.name', line: 'cluster.name: {{ht_cluster_name}}' }
    - { regexp: 'node.name', line: 'node.name: {{hostname}}' }
    - { regexp: 'path.data', line: 'path.data: {{ht_data_path}}' }
    - { regexp: 'path.logs', line: 'path.logs: {{ht_logs_path}}' }
    - { regexp: 'network.host', line: 'network.host: {{ansible_ssh_host}}' }
    - { regexp: 'discovery.zen.ping.unicast.hosts', line: 'discovery.zen.ping.unicast.hosts: {{ht_master_nodes_ips_with_port}}' }
    - { regexp: 'discovery.zen.minimum_master_nodes', line: 'discovery.zen.minimum_master_nodes: 1' }
    - { regexp: 'xpack.security.enabled', line: 'xpack.security.enabled: false' }
  notify: elasticsearch restart

- name: Configure jvm options
  lineinfile: dest="/etc/elasticsearch/jvm.options" regexp="{{item.regexp}}" line="{{item.line}}" state=present backrefs=yes backup=yes
  with_items:
    - { regexp: '-Xms', line: '-Xms{{ht_xms}}' }
    - { regexp: '-Xmx', line: '-Xmx{{ht_xmx}}' }
  notify: elasticsearch restart
