---
- name: Create docker data directory
  file: path={{pl_docker_data}} state=directory

- name: Make sure aufs support is available
  apt: name={{item}} state=present
  with_items:
  - linux-image-extra-{{ansible_kernel}}

- name: Add the docker APT key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: Add the docker source to the APT source list
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ansible_distribution_release}} main' state=present

- name: Install docker
  apt: name={{item}} state=present
  with_items:
  - docker-engine

- name: Install docker python packages
  pip: name={{item.name}} version={{item.version}} state=present
  with_items:
  - { name: docker-py, version: '{{pl_docker_py_version}}' }

- name: Change docker directory
  lineinfile: dest=/lib/systemd/system/docker.service regexp={{item.regexp}} line={{item.line}} state=present backrefs=yes
  with_items:
    - { regexp: 'ExecStart=', line: "ExecStart=/usr/bin/dockerd -g {{pl_docker_data}} -H fd://" }
  notify: restart docker
