---
- name: Create build directory
  file: path='{{pl_docker_packer_build_dir}}' state=directory

- name: Copy template file to build
  copy: src='{{pl_docker_template}}.json' dest='{{pl_docker_packer_build_dir}}/{{pl_docker_template}}.json'

- name: Configure the build template
  lineinfile: dest="{{pl_docker_packer_build_dir}}/{{pl_docker_template}}.json" regexp="{{item.regexp}}" line="{{item.line}}" state=present backrefs=yes backup=yes
  with_items:
    - { regexp: '"repository": ', line: '        "repository": "{{pl_docker_repo_url}}/{{pl_docker_repo_username}}/{{pl_docker_repo_name}}/{{pl_docker_template}}",' }
    - { regexp: '"tag": ', line: '        "tag": "{{pl_tag}}"' }

- name: Build docker image
  shell : packer build '{{pl_docker_template}}.json'
  args:
    chdir: '{{pl_docker_packer_build_dir}}'

- name: Docker repo login
  shell: docker login '{{pl_docker_repo_url}}' --username '{{pl_docker_repo_username}}' --password '{{pl_docker_repo_password}}'

- name: Push image
  shell: docker push '{{pl_docker_repo_url}}/{{pl_docker_repo_username}}/{{pl_docker_repo_name}}/{{pl_docker_template}}:{{pl_tag}}'

- name: Docker repo logout
  shell: docker logout '{{pl_docker_repo_url}}'
