---
- digital_ocean:
    state: present
    command: ssh
    name: "{{ssh_key_name}}"
    ssh_pub_key: "{{ lookup('file', '{{id_rsa_pub}}') }}"
    api_token: "{{digitalocean_api_token}}"
  register: ssh_key

- digital_ocean:
    state: present
    command: droplet
    name: "{{droplet_name}}"
    unique_name: yes
    ssh_key_ids: "{{ssh_key.ssh_key.id}}"
    api_token: "{{digitalocean_api_token}}"
    size_id: "{{droplet_size}}"
    region_id: "{{droplet_region}}"
    image_id: "{{droplet_os}}"
    private_networking: yes
    wait_timeout: 500
  register: droplet

- debug: msg="ID is {{droplet.droplet.id}}"
- debug: msg="IP is {{droplet.droplet.ip_address}}"
