#
#About: This will get list of all regions on DigitalOcean
#
---
- hosts: localhost
  connection: local
  gather_facts: True
  become: yes

  tasks:
  - name: Get list of all regions on DigitalOcean
    shell: curl -X GET -H "Content-Type{{':'}} application/json" -H "Authorization{{':'}} Bearer {{digitalocean_api_token}}" "https{{':'}}//api.digitalocean.com/v2/regions"
    register: optput

  - debug: var=optput.stdout
